### YamlMime:PowerShellCmdlet1
uid: PSDesiredStateConfiguration.Update-DscConfiguration
name: Update-DscConfiguration
module: PSDesiredStateConfiguration
isPreview: false
summary: |-
  Checks the pull server for an updated configuration and applies it.
description: |-
  The `Update-DscConfiguration` cmdlet connects to a pull server, downloads the configuration if it differs from what is current on the node, and then applies the configuration to the computer.

  This cmdlet is available only as part of the [November 2014 update rollup for Windows RT 8.1, Windows 8.1, and Windows Server 2012 R2](https://support.microsoft.com/kb/3000850) from the Microsoft Support library.
parameters:
  cmdletParameters:
  - name: CimSession
    type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Runs the cmdlet in a remote session or on a remote computer.
      Enter a computer name or a session object, such as the output of a [New-CimSession](/powershell/module/cimcmdlets/new-cimsession) or [Get-CimSession](https://learn.microsoft.com/powershell/module/cimcmdlets/get-cimsession) cmdlet.
      The default is the current session on the local computer.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: CimSessionSet
      position: Named
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ComputerName
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies an array of computer names.
      The cmdlet applies the configuration settings to the computers that this parameter specifies.
    aliases:
    - CN
    - ServerName
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ComputerNameSet
      position: "1"
      isRequired: false
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Credential
    type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a user name and password, as a **PSCredential** object, for the target computer.
      To obtain a **PSCredential** object, use the Get-Credential cmdlet.
      For more information, type `Get-Help Get-Credential`.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ComputerNameSet
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: JobName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a friendly name for a job.
      If you specify this parameter, the cmdlet runs as a job, and it returns a **Job** object.

      By default, Windows PowerShell assigns the name JobN where N is an integer.

      If you specify the *Wait* parameter, do not specify this parameter.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ThrottleLimit
    type: <xref href="Int32" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
      If this parameter is omitted or a value of `0` is entered, then Windows PowerShell calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
      The throttle limit applies only to the current cmdlet, not to the session or to the computer.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Wait
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Indicates that the cmdlet blocks the console until it finishes all configuration tasks.

      If you specify this parameter, do not specify the *JobName* parameter.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Update-DscConfiguration
        [[-ComputerName] <String[]>]
        [-Wait]
        [-JobName <String>]
        [-Credential <PSCredential>]
        [-ThrottleLimit <Int32>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: ComputerNameSet
  isDefault: true
- syntax: |-
    ```Syntax
    Update-DscConfiguration
        -CimSession <CimSession[]>
        [-Wait]
        [-JobName <String>]
        [-ThrottleLimit <Int32>]
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: CimSessionSet
  isDefault: false
examples:
- title: 'Example 1: Update a configuration'
  description: |-
    ```
    PS C:\> $Session = New-CimSession -ComputerName "Server01" -Credential ACCOUNTS\PattiFuller
    PS C:\> Update-DscConfiguration -CimSession $Session -Wait
    ```

    The first command creates a CIM session by using the **New-CimSession** cmdlet, and then stores the **CimSession** object in the $Session variable.
    The command prompts you for a password.
    For more information, type `Get-Help New-CimSession`.

    The second command updates the computer specified in the **CimSession** stored in $Session.
    The command specifies the *Wait* parameter.
    The console does not accept additional commands until the current command finishes.
links:
- text: Windows PowerShell Desired State Configuration Overview
  href: https://go.microsoft.com/fwlink/?LinkID=311940
- text: Get-DscConfiguration
  href: Get-DscConfiguration.yml
- text: Get-DscConfigurationStatus
  href: Get-DscConfigurationStatus.yml
- text: Restore-DscConfiguration
  href: Restore-DscConfiguration.yml
- text: Start-DscConfiguration
  href: Start-DscConfiguration.yml
- text: Stop-DscConfiguration
  href: Stop-DscConfiguration.yml
- text: Test-DscConfiguration
  href: Test-DscConfiguration.yml
metadata:
  document type: cmdlet
  external help file: Microsoft.Windows.DSC.CoreConfProviders.dll-Help.xml
  HelpUri: https://learn.microsoft.com/previous-versions/powershell/module/psdesiredstateconfiguration/update-dscconfiguration?view=powershell-5.0&WT.mc_id=ps-gethelp
  Locale: en-US
  Module Name: PSDesiredStateConfiguration
  ms.date: 06/09/2017
  PlatyPS schema version: 2024-05-01
  title: Update-DscConfiguration
